name: Extraction Pollution (ETL)

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  run-etl:
    runs-on: ubuntu-latest 
    
    # --- LA MODIFICATION EST LÀ 👇 ---
    # Cela force GitHub à utiliser la version du futur (Node.js 24) dès maintenant
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    # --------------------------------

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Exécution du script ETL
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SUPABASE_URI: ${{ secrets.SUPABASE_URI }}
        run: python src/data_engineering/fetch_weather.py
