name: Extraction Pollution (ETL)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v5

      - name: Configuration de Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Exécution du script ETL
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SUPABASE_URI: ${{ secrets.SUPABASE_URI }}
        run: python src/data_engineering/fetch_weather.py
